name: Update APIM subscription key

on:
  workflow_dispatch:

jobs:
  update_apim_subscription_key:
    runs-on: ubuntu-latest
    env:
      APIM_SUBSCRIPTION_KEY: ''
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
      - name: Load and extract APIM subscription key
        id: load-and-extract
        run: |
          URL="https://www.enbw.com/elektromobilitaet/produkte/mobilityplus-app/ladestation-finden/map"
          HTML=$(curl -s "$URL")
          APIM_SUBSCRIPTION_KEY=$(echo "$HTML" | grep -oE 'apimSubscriptionKey:[[:space:]]*"[^"]+"' | awk -F'"' '{print $2}')
          echo "APIM_SUBSCRIPTION_KEY=$APIM_SUBSCRIPTION_KEY" >> $GITHUB_ENV
          echo "::set-env name=APIM_SUBSCRIPTION_KEY::$APIM_SUBSCRIPTION_KEY" >> $GITHUB_ENV
      - name: Set GitHub Action Secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'APIM_SUBSCRIPTION_KEY'
          value: ${{ env.APIM_SUBSCRIPTION_KEY }}
          repository: hmanzur/actions-set-secret
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
